### ISSUE TITLE
[FEATURE]Reduce the CPU_IF logic, use only AXI LITE

### ISSUE THREAD

**Issue by roybod** [SystemRDL/PeakRDL-regblock#122]
I have another tool called airhdl.com, that tool show exactly half LUT consumption.
it looks to me that is because of the internal implementation of the CPU_IF.
In the AIRHDL code, the only interface is the AXI LITE.
would you consider adding "remove CPU_IF feature" ?
attaching some results from Vivado 2022.1
PEAKRDL RESULT:
![smec_regs_peakrdl](https://github.com/user-attachments/assets/f2d93283-1acd-4384-8ec5-4e3cb4a03def)
AIRHDL RESULT:
![smec_regs_airhdl](https://github.com/user-attachments/assets/742d7e01-748a-4f78-8cc7-532203f85b46)

**Comment by amykyta3** [comment]
I will look into whether there are specific optimizations to how Vivado interprets PeakRDL-regblock output, but removing features that allow the flexibility of different interface protocols is not an option. That is a core feature of this tool.
