### ISSUE TITLE
Add an option for non structured hwif/cpuif

### ISSUE THREAD

**Issue by saberxt** [SystemRDL/PeakRDL-regblock#16]
As our flow prefer the hardware interface without structure-like interface, do we have possibility to add such an option to generate the hardware interface with every signal declared explicitly?

**Comment by amykyta3** [comment]
I do not have plans to support this.
Struct-like interfaces do a far better job of preserving register name hierarchy and allow me to build towards future planned features like parameterizable register blocks. Explicit hwif signals would require the entire register hierarchy to be flattened and unrolled.
If it helps, I do plan to add support for generating a "hwif report" that would generate a text file of the flattened hwif struct interface (#13)

**Comment by saberxt** [comment]
Got your point, then I think a "hwif report" would be good enough.

Thank you.
