### ISSUE TITLE
common trigger for array of write-buffered registers

### ISSUE THREAD

**Issue by mkahane** [SystemRDL/PeakRDL-regblock#26]
Hi team,
Let's say I have a regfile like this:

```
regfile my_file #(int unsigned ARRAY_SIZE = 8) {
  default accesswidth = 32;
  default regwidth = 32;

  reg {
    field {sw =rw; hw=r} trigger_bit;
  } write_trigger;

  reg {
    regwidth = 64;
    field{ sw=rw; hw=r} wide_field[63:0];
    buffer_writes=true;
  } buffered_regs[ARRAY_SIZE];

};
```

My question is this:

1.) how can I concisely apply the write_trigger to all the buffered regs? The example [here](https://peakrdl-regblock.readthedocs.io/en/latest/udps/write_buffering.html#atomic-group-of-registers) seems to indicate that all triggers need to be set individually

something like 

`buffered_regs[*] -> wbuffer_trigger = write_trigger.trigger_bit;`

**Comment by amykyta3** [comment]
Just omit the array suffix and it will assign to all elements of the array:
```
buffered_regs->wbuffer_trigger = write_trigger.trigger_bit;
```

This is actually the only supported way at the moment. The compiler [doesn't support assigning individual array elements](https://systemrdl-compiler.readthedocs.io/en/stable/known_issues.html#no-support-for-heterogeneous-arrays) yet.

**Comment by mkahane** [comment]
roger. Thanks, Alex!
