### ISSUE TITLE
Add support for field encoding property

### ISSUE THREAD

**Issue by apstrike** [SystemRDL/PeakRDL-regblock#29]
Hi, I was wondering if there are any plans in the works for adding support for the field encoding property?

Thanks

**Comment by amykyta3** [comment]
I hadn't prioritized it, but yes that should be pretty easy to add.

**Comment by amykyta3** [comment]
@hughjackson - I had noticed that you have a fork where [you added enum support](https://github.com/hughjackson/PeakRDL-regblock/tree/enum_support) some time ago. Is that functional?
I wonder if you'd be interested in contributing your work here.

**Comment by hughjackson** [comment]
I'd definitely be interested in contributing. It's been a while since I looked at it, I will try to get it back in line with main. I think I was having some trouble with adding the unit test, so I might ask for some help on that.

**Comment by amykyta3** [comment]
Don't worry about it. I'll pull your changes in and make the required changes.
Thanks!

**Comment by amykyta3** [comment]
Tidied up, squashed and merged to the main branch.
This will be included in the next release (after I burn through some of the other features)

Thanks again @hughjackson! Only needed some very minor changes for this to work cleanly.

**Comment by amykyta3** [comment]
Published in `v0.13.0`
