### ISSUE TITLE
fatal: Incompatible assignment to property 'hwenable'

### ISSUE THREAD

**Issue by rakesh2215** [SystemRDL/PeakRDL-regblock#45]
Greetings.

Searching for this error led me to this:

https://github.com/SystemRDL/systemrdl-compiler/issues/31

So this error is fixed in systemrdl-compiler, but not in PeakRDL-regblock?

Additionally, I tried to test only systemrdl-compiler as below:

`./print_hierarchy.py <my_rdl>
`
It still gave same error.

RDL snippet:

```
field status_field {
   sw = rw; 
   hw = w;
   we; 
   hwenable;
   woclr;
};
```

It's a fresh installation, so I have all latest.

```
python3 -m pip install peakrdl-regblock 
Collecting peakrdl-regblock
  Using cached peakrdl_regblock-0.15.0-py3-none-any.whl
Collecting systemrdl-compiler>=1.25.1
  Downloading systemrdl_compiler-1.26.0-cp39-cp39-macosx_10_13_x86_64.whl (1.2 MB)
```

**Comment by amykyta3** [comment]
https://github.com/SystemRDL/systemrdl-compiler/issues/31 is unrelated. That was a bug that was fixed nearly 4 years ago.

This is an issue in your RDL - It is only legal to assign `hwenable` a reference. You are assigning it a boolean.
See the SystemRDL spec:
![image](https://github.com/SystemRDL/PeakRDL-regblock/assets/12021539/8a6a5c0b-b10a-49a4-9ce0-73b5fa820426)
