### ISSUE TITLE
Making bit widths of vectors the same when doing comparisons

### ISSUE THREAD

**Issue by leolitenstorrent** [SystemRDL/PeakRDL-regblock#49]
Hello PeakRDL Development Team,

Is it possible that, in the future versions, the bit widths of vectors be set to the same in comparisons? For example, `cpuif_req_masked & (cpuif_addr == 'h0)` can become `cpuif_req_masked & (cpuif_addr == 8'h0)` when the address width is 8. I know there are other parts of the script that generate these comparisons, and I wish these can be improved as well.

I and my team are currently seeing many warning messages about bit widths of vectors not matching during our simulations, and thus we kindly wish the improvement can be made. We appreciate your consideration.

Thank you very much!

**Comment by amykyta3** [comment]
I have adjusted the code generator to generate sized integers in nearly all cases I could find.

I'm curious - can you share which simulator you are using that generates these warnings?

**Comment by leolitenstorrent** [comment]
Hello Alex,

I am using Synopsys's VCS with lint options enabled such that warnings like unmatched bit-widths, permanently enabled flops, etc. are reported.

**Comment by amykyta3** [comment]
Fixed in v0.16.0
