### ISSUE TITLE
Removing "if(1)" Conditions

### ISSUE THREAD

**Issue by leolitenstorrent** [SystemRDL/PeakRDL-regblock#50]
Hello Alex,

I noticed that for single pulse registers, PeakRDL-regblock is generating `if(1)` conditions for resetting the registers back to 0, such as in the code below.
```
            ....
            load_next_c = '1;
        end else if(1) begin // singlepulse clears back to 0
            next_c = '0;
            load_next_c = '1;
        end
```
May I request that the `if(1)` conditions be omitted for singlepulse registers (and other components/registers), because it generates warning messages and has the possibility to cause synthesizers to generate extra logic?

Thank you!

**Comment by amykyta3** [comment]
Agree this should be cleaned up.

The generator code even [has a `TODO` comment for this exact thing](https://github.com/SystemRDL/PeakRDL-regblock/blob/main/src/peakrdl_regblock/field_logic/sw_singlepulse.py#L14-L16). Thanks for the reminder :smile:!

**Comment by amykyta3** [comment]
Will be fixed in next release
