### ISSUE TITLE
Use scalar if conditions

### ISSUE THREAD

**Issue by leolitenstorrent** [SystemRDL/PeakRDL-regblock#54]
Hello Alex,

May you make the conditions for if statements scalars instead of vectors (see image below)? This has been causing Spyglass Lint to generate warning messages. Thank you!

![image](https://github.com/SystemRDL/PeakRDL-regblock/assets/136389268/830f1a2a-2603-4008-9c3d-fa21280c9f04)

**Comment by amykyta3** [comment]
Will do. In this case, I can change the `^` to `!=` for equivalent behavior.

Is this the only situation where this type of warning was flagged?

**Comment by leolitenstorrent** [comment]
Hello,

Thank you! I remember this type of waring is also flapped for the interrupt capture conditions of posedge and negedge interrupt registers.

**Comment by amykyta3** [comment]
Thanks. Will be fixed in the next release.
