### ISSUE TITLE
Support for packed structs

### ISSUE THREAD

**Issue by leolitenstorrent** [SystemRDL/PeakRDL-regblock#64]
Hello Alex,

May PeakRDL have an option to support packed structs?

I understand that unpacked structs has the advantage of preventing assignment mistakes. However, packed structs are versatile as they allow a register, for exampled, to be assigned as a whole. This is especially useful when testing the RTL using a testbench, etc.

Thus, may there be an option, for example, in the exporter to support this feature?

I and my team would appreciate it very much! Thanks!

**Comment by amykyta3** [comment]
Nothing prevents you from assigning unpacked structs as a whole as well.

Try using the default assignment mechanism for initializing:
```systemverilog
packed_struct = '{default: '0};
```

Or use the streaming operator if you want to assign a vector into a packed struct:
```systemverilog
packed_struct = {>>{64'h12345678ABCD9876}};
```

I expect these widely supported methods will work for you.

**Comment by leolitenstorrent** [comment]
Noted. Thank you!
